// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"rs04nfn644","name":"grudgesCRUD","description":"","endpoint":"https://rs04nfn644.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/grudges","/grudges/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:ce3e4e2c-27f5-487b-a50f-330140a400a7',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'grudges-hosting-mobilehub-274238864',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1cxk6bu50jddz.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"grudges-mobilehub-274238864-grudges","attributes":[{"name":"userId","type":"S"},{"name":"id","type":"S"},{"name":"avenged","type":"BOOL"},{"name":"deed","type":"S"},{"name":"person","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"id"}],
    'aws_mandatory_sign_in': 'enable',
    'aws_project_id': 'a2021c70-bfb5-4ecc-ac0c-e86727616ad2',
    'aws_project_name': 'grudges-2018-07-19-13-05-04',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'grudges-deployments-mobilehub-274238864',
    'aws_resource_name_prefix': 'grudges-mobilehub-274238864',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_MdnZjCtK3',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2v1p55s1jpaa7h0qbkdal7tapv',
}

export default awsmobile;
